### ISSUE TITLE
python train.py

### ISSUE THREAD

**Issue by seekingdeep** [tson1997/LSM#2]
@tson1997 Hi there,

getting an error at training
```
(udet) home@home-lnx:~/programs/Line-Segmentation-Model$ python train.py
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    trainer.train()
  File "/home/home/programs/Line-Segmentation-Model/trainer/trainer.py", line 36, in train
    self.train_step()
  File "/home/home/programs/Line-Segmentation-Model/trainer/trainer.py", line 40, in train_step
    for i, data in enumerate(self.data_loader):
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/programs/Line-Segmentation-Model/datasets/image_dataset.py", line 126, in __getitem__
    image, gt   = self._preprocess(image, gt, 0.5)
TypeError: _preprocess() takes 3 positional arguments but 4 were given
```

**Comment by sonnguyenasu** [comment]
Hello,
Thanks for reporting, it’s a bug in dataset function. I will update it ASAP
