### ISSUE TITLE
'numpy.ndarray' object has no attribute 'unsquueze'

### ISSUE THREAD

**Issue by seekingdeep** [tson1997/LSM#7]
Hi there,
When training using the [SROIE dataset](https://drive.google.com/file/d/1A4HInWUFgHfJpLfRv0pCtOAqNREiSl0G/view?usp=sharing), i get error.
[similar discussion](https://stackoverflow.com/questions/68319216/attributeerror-numpy-ndarray-object-has-no-attribute-unsqueeze)
Note: [`unsquueze`](https://github.com/tson1997/Line-Segmentation-Model/blob/main/datasets/image_dataset.py#L99) should be `unsqueeze`

```
(udet) home@home-lnx:~/programs/Line-Segmentation-Model/Line-Segmentation-Model$ python train.py -e 100000
Iteration: 2, loss: 0.5959722399711609
Iteration: 12, loss: 0.3670177459716797
Iteration: 22, loss: 0.41324764490127563
Iteration: 32, loss: 0.3334452509880066
Iteration: 42, loss: 0.24350987374782562
Iteration: 52, loss: 0.38365432620048523
Iteration: 62, loss: 0.21088488399982452
Iteration: 72, loss: 0.27554211020469666
Iteration: 82, loss: 0.2722679376602173
Iteration: 92, loss: 0.1982157826423645
Iteration: 102, loss: 0.31656327843666077
Iteration: 112, loss: 0.2304714024066925
Iteration: 122, loss: 0.2331867218017578
Iteration: 132, loss: 0.2439255714416504
Traceback (most recent call last):
  File "train.py", line 39, in <module>
    trainer.train()
  File "/home/home/programs/Line-Segmentation-Model/Line-Segmentation-Model/trainer/trainer.py", line 36, in train
    self.train_step()
  File "/home/home/programs/Line-Segmentation-Model/Line-Segmentation-Model/trainer/trainer.py", line 40, in train_step
    for i, data in enumerate(self.data_loader):
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 385, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/anaconda3/envs/udet/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/home/programs/Line-Segmentation-Model/Line-Segmentation-Model/datasets/image_dataset.py", line 126, in __getitem__
    image, gt   = self._preprocess(image, gt)
  File "/home/home/programs/Line-Segmentation-Model/Line-Segmentation-Model/datasets/image_dataset.py", line 99, in _preprocess
    img_nd = img_nd.unsquueze(axis=2)
AttributeError: 'numpy.ndarray' object has no attribute 'unsquueze'
```

**Comment by sonnguyenasu** [comment]
Hi, I have made an update on this issue. Apparently, I just added the line for handling gray images and my dataset doesn't have one so I don't have knowledge of this bug. Thanks for reporting.

**Comment by seekingdeep** [comment]
Thanks!! the new commit solved the issue.
